#define CHOOSEUNIFORM_IDD_DIALOG        8000
#define CHOOSEUNIFORM_IDC_ITEM0         8001
#define CHOOSEUNIFORM_IDC_ITEM1         8002
#define CHOOSEUNIFORM_IDC_ITEM2         8003
#define CHOOSEUNIFORM_IDC_REROLL        8101
#define CHOOSEUNIFORM_IDC_CONFIRM       8102
#define CHOOSEUNIFORM_IDC_COUNTDOWN     8200


#define CHOOSEUNIFORM_PADDING_W         (0.002 * X_SCALE)
#define CHOOSEUNIFORM_PADDING_H         (0.010 * Y_SCALE)
#define CHOOSEUNIFORM_SPACER_W          (0.002 * X_SCALE)

#define CHOOSEUNIFORM_TOPBAR_H          (0.040 * Y_SCALE)
#define CHOOSEUNIFORM_TOPBAR_SPACER_H   (0.002 * Y_SCALE)

#define CHOOSEUNIFORM_COLUMN_W          (0.200 * X_SCALE)
#define CHOOSEUNIFORM_COLUMN_H          (0.200 * Y_SCALE)

#define CHOOSEUNIFORM_TOTAL_W           (2 * CHOOSEUNIFORM_PADDING_W + 3 * CHOOSEUNIFORM_COLUMN_W + 2 * CHOOSEUNIFORM_SPACER_W)
#define CHOOSEUNIFORM_TOTAL_H           (2 * CHOOSEUNIFORM_PADDING_H + CHOOSEUNIFORM_COLUMN_H)

#define CHOOSEUNIFORM_X                 CENTER(1,CHOOSEUNIFORM_TOTAL_W)
#define CHOOSEUNIFORM_Y                 CENTER(1,CHOOSEUNIFORM_TOTAL_H)
